# Generated by Django 5.0.1 on 2026-02-11 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DOCUMENT_EXPIRY', 'Document Expiry Alert'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('STORAGE_WARNING', 'Storage Warning'), ('STORAGE_CRITICAL', 'Storage Critical'), ('SECURITY_ALERT', 'Security Alert'), ('NEW_DEVICE_LOGIN', 'New Device Login'), ('SYSTEM', 'System Notification')], db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('encrypted_title', models.BinaryField()),
                ('encrypted_body', models.BinaryField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_expiry_alerts', models.BooleanField(default=True)),
                ('email_storage_alerts', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_expiry_alerts', models.BooleanField(default=True)),
                ('push_storage_alerts', models.BooleanField(default=True)),
                ('push_security_alerts', models.BooleanField(default=True)),
                ('alert_30_days', models.BooleanField(default=True)),
                ('alert_15_days', models.BooleanField(default=True)),
                ('alert_7_days', models.BooleanField(default=True)),
                ('alert_1_day', models.BooleanField(default=True)),
                ('alert_on_expiry', models.BooleanField(default=True)),
                ('storage_warning_threshold', models.IntegerField(default=80)),
                ('storage_critical_threshold', models.IntegerField(default=95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
