# Generated by Django 5.0.1 on 2026-02-11 16:22

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Hash of email for authentication', max_length=255, unique=True)),
                ('email', models.EmailField(help_text="User's email address (for verification and login)", max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text='Mobile number with country code (e.g., +911234567890)', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_verified', models.BooleanField(default=False, help_text='Whether email address is verified')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True)),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth user ID', max_length=255, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('local', 'Local (Email/Password)'), ('google', 'Google OAuth')], default='local', help_text='How user registered', max_length=20)),
                ('recovery_key_hash', models.CharField(blank=True, help_text='SHA-256 hash of recovery key', max_length=64)),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('FAMILY', 'Family'), ('LIFETIME', 'Lifetime')], default='FREE', help_text="User's subscription level", max_length=20)),
                ('storage_used', models.BigIntegerField(default=0, help_text='Total storage used in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Client-generated unique device identifier', max_length=255, unique=True)),
                ('device_name', models.CharField(help_text='User-friendly device name', max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android App'), ('ios', 'iOS App')], default='web', max_length=50)),
                ('is_trusted', models.BooleanField(default=False, help_text='Whether this device is verified and trusted')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last time this device was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-last_active'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
