# Generated by Django 5.0.1 on 2026-02-11 16:22

import django.db.models.deletion
import uuid
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Category name (e.g., 'Identity Documents')", max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'db_table': 'document_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_name', models.TextField(help_text='Client-encrypted folder name (base64 string)')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code (e.g., #3b82f6)', max_length=7)),
                ('icon', models.CharField(default='📁', help_text='Folder icon (emoji)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this folder belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='vault.documentcategory')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder (null for root folders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='vault.folder')),
                ('user', models.ForeignKey(help_text='Owner of this folder', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'db_table': 'folders',
                'ordering': ['encrypted_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_title', models.TextField(blank=True, default='', help_text='Client-encrypted document title (base64 string)')),
                ('encrypted_description', models.TextField(blank=True, default='', help_text='Client-encrypted description (base64 string)')),
                ('encrypted_doc_type', models.TextField(blank=True, default='', help_text='Client-encrypted document type (base64 string)')),
                ('encrypted_file', models.FileField(help_text='Encrypted document file', upload_to=vault.models.document_upload_path)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_extension', models.CharField(help_text='Original file extension', max_length=10)),
                ('mime_type', models.CharField(default='application/octet-stream', help_text='MIME type of original file', max_length=100)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of encrypted file', max_length=64)),
                ('has_expiry', models.BooleanField(default=False, help_text='Whether document has expiry date')),
                ('encrypted_issue_date', models.TextField(blank=True, default='', help_text='Client-encrypted issue date (base64 string)')),
                ('encrypted_expiry_date', models.TextField(blank=True, default='', help_text='Client-encrypted expiry date (base64 string)')),
                ('notification_trigger_timestamp', models.DateTimeField(blank=True, help_text='Timestamp for notification scheduling', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vault.documentcategory')),
                ('folder', models.ForeignKey(blank=True, help_text='Optional folder for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vault.folder')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Sequential version number (1, 2, 3...)')),
                ('encrypted_file', models.FileField(help_text='Encrypted file for this version', upload_to=vault.models.document_upload_path)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('encrypted_change_notes', models.TextField(blank=True, default='', help_text='Client-encrypted notes about changes (base64 string)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.document')),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'category'], name='folders_user_id_fbff9d_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'parent'], name='folders_user_id_0d7266_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'is_deleted'], name='documents_user_id_c8c388_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'category'], name='documents_user_id_5f3555_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'folder'], name='documents_user_id_a6774d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['notification_trigger_timestamp'], name='documents_notific_ba2d97_idx'),
        ),
    ]
